### ISSUE TITLE
Arch check in getContainer will always fail

### ISSUE THREAD

**Issue by kyubisation** [freaktechnik/get-firefox#30]
https://github.com/freaktechnik/get-firefox/blob/47b1766dae1c68010ec1855592291e55c65f7143/index.js#L156

I think this line should be:
`
if(!(arch in spec.arches)) {
`

**Comment by freaktechnik** [comment]
Seems like it. Thanks for pointing that out! I wonder how I was able to download non-default arch packages before...

**Comment by kyubisation** [comment]
No problem. Thanks for the quick response.
It's not critical to me at the moment, as I'm currently just testing a few things.

**Comment by kyubisation** [comment]
Danke dir für's schnälle fixe!

**Comment by freaktechnik** [comment]
I've just pushed a patch release to npm that fixes this.

**Comment by kyubisation** [comment]
Thank you very much :-)
