### ISSUE TITLE
how to best use this with CircleCi?

### ISSUE THREAD

**Issue by gregglind** [freaktechnik/get-firefox#42]
Code examples welcome.

**Comment by freaktechnik** [comment]
I honestly have no idea as I've never used CCI. But I'd assume you'd use it exactly the same way as any npm CLI tool.

**Comment by peterbe** [comment]
Here is a working example: https://github.com/mozilla/normandy/blob/ca3289dfd151779c71d0909877e460f7c463994d/ci/run.sh#L37-L39

This is inside a Docker container based on `python-3.6-slim` which is Debian Stretch. 
The commands are:
```bash
# This makes sure all the libs are available
apt install -y --no-install-recommends firefox-esr
npm install -g get-firefox
get-firefox -e
./firefox/firefox --version
```

**Comment by peterbe** [comment]
The only bad thing is that the cute interactive CLI output does poorly in CircleCI.
There's about 2-3 pages of this kind of output:
<img width="666" alt="screen shot 2018-08-06 at 10 48 05 am" src="https://user-images.githubusercontent.com/26739/43723724-53410504-9966-11e8-9202-970e437041c8.png">

**Comment by freaktechnik** [comment]
Hm, the lib that does that should detect circle CI, I'll look into how to better handle that. Thank you for the example!

**Comment by peterbe** [comment]
I filed https://github.com/freaktechnik/get-firefox/issues/56 we can discuss there.
