### ISSUE TITLE
Non-interactive cli output

### ISSUE THREAD

**Issue by peterbe** [freaktechnik/get-firefox#56]
When using this tool in CircleCI the stdout is logged to files and the output becomes excessively verbose. See:
<img width="666" alt="screen shot 2018-08-06 at 10 48 05 am" src="https://user-images.githubusercontent.com/26739/43723786-7c8a3d90-9966-11e8-8eb1-697b8a457a22.png">

The ideal thing would be to be able to run `get-firefox --non-interactive ...` or something.

**Comment by peterbe** [comment]
Ideally, we should look for the environment variable `CI=true` (or `CI=1`) to see if we're in CI and if that's true, don't get fancy with the output.

**Comment by freaktechnik** [comment]
This is fixed with 2.2.0. There is now a `--verbose` flag, that uses a log-style renderer and the flag is set by default in CI environments.
